### ISSUE TITLE
how get the coordinates embeddings

### ISSUE THREAD

**Issue by lingxitong** [invoker-LL/LongMIL#2]
if __name__ == "__main__":
    data = torch.randn((12800, 384+2)).cuda() # 384 is feature, 2 is coordinates
    model = LongMIL(n_classes=2).cuda()
    print(model.eval())
    results_dict = model(data)
    # pdb.set_trace()
    print(results_dict)

Hello,Nice work,Can you tell me how to get the external 2 coordinates embeddings?

**Comment by invoker-LL** [comment]
During patching, e.g. in CLAM, there are coordinates saved.  
It is also saved during feature extraction (https://github.com/mahmoodlab/CLAM/blob/8455dc8c4623f8881281c65a3725bbdad99fb59e/extract_features_fp.py#L113).

**Comment by lingxitong** [comment]
ok.thanks
